In [3]:
import requests
import pandas as pd

In [4]:
# My NYT API key
api_key = "MY_NYT_API_KEY"

In [5]:
# This cell connects to the NYT Most Popular API
url = "https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json"

params = {
    "api-key": api_key
}

response = requests.get(url, params=params)

# Check if the request worked
print(response.status_code)

200

In [6]:
# This cell reads the JSON data from the API
data = response.json()

# Show the main keys in the JSON
print(data.keys())

# Show how many articles were returned
print(len(data["results"]))

dict_keys(['status', 'copyright', 'num_results', 'results'])
20

In [7]:
# This cell turns the NYT results into a pandas DataFrame
df = pd.DataFrame(data["results"])

# Show the column names
print(df.columns.tolist())

# Show the first 5 rows
df.head()

['uri', 'url', 'id', 'asset_id', 'source', 'published_date', 'updated', 'section', 'subsection', 'nytdsection', 'adx_keywords', 'column', 'byline', 'type', 'title', 'abstract', 'des_facet', 'org_facet', 'per_facet', 'geo_facet', 'media', 'eta_id']

,uri,url,id,asset_id,source,published_date,updated,section,subsection,nytdsection,...,byline,type,title,abstract,des_facet,org_facet,per_facet,geo_facet,media,eta_id
0,nyt://article/c6262605-4132-560e-a13d-328918cb...,https://www.nytimes.com/2026/04/14/us/politics...,100000010841613,100000010841613,New York Times,2026-04-14,2026-04-15 13:19:41,U.S.,Politics,u.s.,...,By Anton Troianovski,Article,Vance Says the Pope Should Be More Careful Whe...,"The vice president, who is Catholic, took issu...","[US and Israeli Attack on Iran (2026), United ...",[Roman Catholic Church],"[Leo XIV, Vance, J D, Trump, Donald J]",[Iran],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
1,nyt://article/33dd1862-75ea-5a77-906a-0e2d4874...,https://www.nytimes.com/2026/04/15/arts/televi...,100000010841774,100000010841774,New York Times,2026-04-15,2026-04-15 07:31:20,Arts,Television,arts,...,By Trish Bendix,Article,Late Night Laughs at Explanations of Trump’s J...,Ronny Chieng poked fun at JD Vance’s defense o...,[Television],[],"[Colbert, Stephen, Kimmel, Jimmy, Chieng, Ronn...",[],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
2,nyt://article/7795da53-c76d-5d86-b8f6-63e6c966...,https://www.nytimes.com/2026/04/14/us/politics...,100000010841614,100000010841614,New York Times,2026-04-14,2026-04-15 17:22:22,U.S.,Politics,u.s.,...,By Chris Cameron,Article,Vance Heckled in Antiwar Protest at Turning Po...,Vice President JD Vance appeared to express sy...,"[United States Politics and Government, US and...",[Turning Point USA],"[Trump, Donald J, Vance, J D]","[Iran, Middle East]",[],0
3,nyt://article/a3cd5a33-6697-53f8-93a4-1a7e432e...,https://www.nytimes.com/2026/04/15/opinion/art...,100000010833881,100000010833881,New York Times,2026-04-15,2026-04-15 16:47:57,Opinion,,opinion,...,By Colson Whitehead,Article,Don’t Use A.I. to Do This,People are usually surprised when I admit that...,"[Artificial Intelligence, Books and Literature...",[],"[Wolf, Dick]",[],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
4,nyt://article/db1a6ed9-380c-5e9a-8d3c-914bde4d...,https://www.nytimes.com/2026/04/14/us/florida-...,100000010840508,100000010840508,New York Times,2026-04-14,2026-04-15 12:31:30,U.S.,,u.s.,...,By Vjosa Isai,Article,Surgeon Who Removed Wrong Organ From Patient I...,Dr. Thomas Shaknovsky tried to persuade his co...,"[Malpractice, Surgery and Surgeons, Deaths (Fa...",[],[],"[Miramar (Fla), Walton County (Fla)]","[{'type': 'image', 'subtype': 'photo', 'captio...",0

In [8]:
# This cell keeps only the columns I want to show clearly
df_clean = df[[
    "title",
    "published_date",
    "section",
    "byline",
    "source",
    "url"
]]

# Show the cleaned DataFrame
df_clean.head()

,title,published_date,section,byline,source,url
0,Vance Says the Pope Should Be More Careful Whe...,2026-04-14,U.S.,By Anton Troianovski,New York Times,https://www.nytimes.com/2026/04/14/us/politics...
1,Late Night Laughs at Explanations of Trump’s J...,2026-04-15,Arts,By Trish Bendix,New York Times,https://www.nytimes.com/2026/04/15/arts/televi...
2,Vance Heckled in Antiwar Protest at Turning Po...,2026-04-14,U.S.,By Chris Cameron,New York Times,https://www.nytimes.com/2026/04/14/us/politics...
3,Don’t Use A.I. to Do This,2026-04-15,Opinion,By Colson Whitehead,New York Times,https://www.nytimes.com/2026/04/15/opinion/art...
4,Surgeon Who Removed Wrong Organ From Patient I...,2026-04-14,U.S.,By Vjosa Isai,New York Times,https://www.nytimes.com/2026/04/14/us/florida-...

In [9]:
# This cell shows the size of my cleaned DataFrame
print("Rows and columns:", df_clean.shape)

# This cell shows the data types
print(df_clean.dtypes)

Rows and columns: (20, 6)
title             object
published_date    object
section           object
byline            object
source            object
url               object
dtype: object

### Summary

In this assignment, I used the New York Times Most Popular API. I sent a request to the API, read the JSON response, and converted the results into a pandas DataFrame. Then I selected useful columns like title, published date, section, byline, source, and url to make the data easier to read.

Note: I removed my private NYT API key before submission for security. The notebook was run successfully before removing the key, and the outputs are shown above. To rerun this notebook, enter a valid NYT API key in the api_key variable.